services:
  backend:
    build: ./backend
    container_name: backend
    image: ghcr.io/arquisoft/identity-exposure-tfg-backend:latest
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    networks:
      - monitor-net

  webapp:
    build:
      context: ./webapp
      args:
        - VITE_API_URL=http://localhost:3000
    container_name: webapp
    image: ghcr.io/arquisoft/identity-exposure-tfg-webapp:latest
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - monitor-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./backend/monitoring/prometheus:/etc/prometheus
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "9091:3000"
    volumes:
      - ./backend/monitoring/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitor-net

networks:
  monitor-net:
    driver: bridge
