sonar.organization=tu-organizacion-sonarcloud
sonar.host.url=https://sonarcloud.io
sonar.projectKey=tu-usuario_identity-exposure-tfg
sonar.projectName=identity-exposure-tfg

sonar.sources=webapp/src,users/app
sonar.tests=webapp/src/__tests__,users/tests
sonar.test.inclusions=**/*.test.tsx,**/test_*.py
sonar.exclusions=users/app/**/__pycache__/**
sonar.javascript.lcov.reportPaths=webapp/coverage/lcov.info
sonar.python.coverage.reportPaths=users/coverage.xml
sonar.python.version=3.12
